name: Java Maven Test

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Test with Maven
        run: mvn -B test --file ./audience-module-console/pom.xml
